### PR TITLE
Removed the word link between Atlas and external link icon #416

### PR DESCRIPTION
**Pull request by AZBL**
Removed the word link between Atlas and external link icon from the map detail page.

### CODE REVIEW

**Comment by AZBL** [comment]
@Moylena

**Comment by Moylena** [comment]
@thansidwell  are you able to support this please?

**Comment by Moylena** [comment]
@thansidwell  would you be able to help with this?

**Comment by thansidwell** [comment]
@AZBL @Moylena I don't see anywhere to view a preview of it. It is such a low-risk change I think we can just approve it without seeing it.

**Review by brandonfcohen1 — APPROVED** [review]

**Pull request merged**
