### PR TITLE
Jgaye/261 set max width and min padding

### PR DESCRIPTION
**Pull request by jgaye**
For #261 

Second try:  
Updated all pages on 1 column to have a max-width of 1024 px, and a min padding of 20px on mobile.

@thansidwell

### CODE REVIEW

**Review by paulhchoi — APPROVED** [review]
@jgaye this is great! as a nit, have you considered utilizing [next.js's `layout.tsx`](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#layouts) to DRY up this code? You could feasibly just add these classes to a single wrapper div in a `layout.tsx`, and have all the pages just inherit these classes?

Approving b/c it completes the ticket, but try the `layout.tsx` suggestion if you're up for it!

**Comment by jgaye** [comment]
> @jgaye this is great! as a nit, have you considered utilizing [next.js's `layout.tsx`](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#layouts) to DRY up this code? You could feasibly just add these classes to a single wrapper div in a `layout.tsx`, and have all the pages just inherit these classes?
> 
> Approving b/c it completes the ticket, but try the `layout.tsx` suggestion if you're up for it!

I am up for it, I was wondering if there way a way indeed. I will try to improve before merging

**Comment by jgaye** [comment]
> > @jgaye this is great! as a nit, have you considered utilizing [next.js's `layout.tsx`](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#layouts) to DRY up this code? You could feasibly just add these classes to a single wrapper div in a `layout.tsx`, and have all the pages just inherit these classes?
> > Approving b/c it completes the ticket, but try the `layout.tsx` suggestion if you're up for it!
> 
> I am up for it, I was wondering if there way a way indeed. I will try to improve before merging



> > @jgaye this is great! as a nit, have you considered utilizing [next.js's `layout.tsx`](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#layouts) to DRY up this code? You could feasibly just add these classes to a single wrapper div in a `layout.tsx`, and have all the pages just inherit these classes?
> > Approving b/c it completes the ticket, but try the `layout.tsx` suggestion if you're up for it!
> 
> I am up for it, I was wondering if there way a way indeed. I will try to improve before merging

@paulhchoi I've updated the RootLayout, but I have a problem with the map page that should have a totally different layout (i.e. take the whole width of the page). Is there a way to 'cancel' the style of the RootLayout in the MapLayout?

**Comment by jgaye** [comment]
@paulhchoi , with my last commit I have a solution using 1 blank RooLayout and then a TextContentLayout reused for each page.  
It's just slightly DRYer, but you would still have to be sure to use the TextContetnLayout for each page. WDYT?

**Review by thansidwell — APPROVED** [review]
Looks good!

**Review by thansidwell — CHANGES_REQUESTED** [review]
I noticed that map page got the min-width on the pages as well. It shouldn't! 

CleanShot 2024-03-21 at 00 18 18@2x

**Comment by paulhchoi** [comment]
> @paulhchoi , with my last commit I have a solution using 1 blank RooLayout and then a TextContentLayout reused for each page.
> It's just slightly DRYer, but you would still have to be sure to use the TextContetnLayout for each page. WDYT?

Ah I see, I didn't anticipate the "map vs copy pages" layout differences — tbh I'm not a fan of enforcing the usage of a separate `<TextContentLayout />` component every time you'd want the correct padding, as its highly likely someone would forget it when adding a new page. I'd prefer just using the template `layout.tsx` that implicitly wraps all of the nested pages. With separate layouts between the full-width 'map' vs the padding-included 'content' pages, we could utilize Next.js's [route groups](https://nextjs.org/docs/app/building-your-application/routing/colocation#route-groups), and create a content-page-only route group with a `layout.tsx` in it that would wrap the content pages with extra padding. This may look like:

- Moving all 'content pages' into a 'content page' route group `src/app/(content-pages)/`.
- Creating a file `src/app/(content-pages)/layout.tsx`
- Adding something like the following in it:
```
<div className="flex flex-col min-h-screen">
  <div className="flew-grow container mx-auto pt-20 **max-w-5xl p-5**"> // <- your classes here
    {children}
  </div>
</div>
```
- and then removing the 'wrapper classes' like the above in the individual pages, and just having `React.Fragments` / `<></>` 's wrap the individual pages (eg.: in the get-access page, which would now be at `src/app/(content-pages)/get-access/`, the page component would start with: 
```
export default function GetAccessPage() {
  return (
    <>
      <h1 className="heading-3xl font-bold mb-6">Get Access</h1>
      ...
```

This would de-duplicate the code and make it much easier to add additional pages without having to possibly forgetting to add an explicit layout component or forgetting to copy-paste the classes, etc. And for the `/map/` page, it'd still be at `src/app/map`, where our newly added route group layout wouldn't affect it. Hope this helps!

**Review by brandonfcohen1 — CHANGES_REQUESTED** [review]
@jgaye can you fix merge conflicts?

**Comment by brandonfcohen1** [comment]
> @jgaye can you fix merge conflicts?

@jgaye any update here?

**Comment by Moylena** [comment]
@jgaye  checking in on this!

**Pull request closed without merging**
