### PR TITLE
fix: Update footer markup structure for accessibility

### PR DESCRIPTION
**Pull request by markgoetz**
This PR updates the footer markup for accessibility per #201.

### CODE REVIEW

**Comment by markgoetz** [comment]
The `header` tag is actually hardcoded into NextUI's Navbar component(per [their repo](https://github.com/nextui-org/nextui/blob/main/packages/components/navbar/src/navbar.tsx)), so unfortunately I had to remove it from this component.

**Comment by bacitracin** [comment]
> The `header` tag is actually hardcoded into NextUI's Navbar component(per [their repo](https://github.com/nextui-org/nextui/blob/main/packages/components/navbar/src/navbar.tsx)), so unfortunately I had to remove it from this component.

Ah, actually we talked about this in the last meeting, some of the NextUI components aren't all there a11y-wise, so we want to empower devs to feel free to rewrite components from scratch if the NextUI component has issues.

**Review by bacitracin — APPROVED** [review]
👍

**Comment by bacitracin** [comment]
@markgoetz oh wait do you mind updating your base against staging instead of master?

**Comment by markgoetz** [comment]
> @markgoetz oh wait do you mind updating your base against staging instead of main?
Oops, good call!  This is done now.

**Pull request merged**
