### PR TITLE
Semantic updates that will help screenreader users + keyboard navigation.

### PR DESCRIPTION
**Pull request by JosephAni**
# Pull Request Title

## Checklist:

- Swap header and nav order. Nav inside of header
- Remove the list that wraps the logo. 
- Added an aria-label of "primary" to the nav tag.

### CODE REVIEW

**Comment by marvieqa** [comment]
@JosephAni
In the latest build, the header looks broken:

Screenshot 2024-03-25 at 16 20 53

**Comment by JosephAni** [comment]
@marvieqa I am aware of the positioning; I just want a heads up, if I am using the right semantic code.

**Comment by marvieqa** [comment]
@JosephAni gotcha, sorry I misunderstood thinking this is all it. Ran the screen reader and the landmarks banner and navigation, plus the list of links are all announced correctly. One small thing that stood out is the Clean & Green Philly logo link is announced by its link address. Would you mind adding `<aria-label="Clean and Green Philly - Home>` in the link to make it descriptive?

**Comment by JosephAni** [comment]
Sure thing!

**Review by brandonfcohen1 — CHANGES_REQUESTED** [review]
@JosephAni any update here? Also can you update your packages to fix merge conflicts?

**Comment by brandonfcohen1** [comment]
> @JosephAni any update here? Also can you update your packages to fix merge conflicts?

@JosephAni any update on this?

**Pull request closed without merging**
