### PR TITLE
feat(507): show all "Get Property Access" options

### PR DESCRIPTION
**Pull request by paulhchoi**
## Description

This PR makes all the "Property Access" options visible with styling based on the [figma prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592%3A30687&mode=design&t=TMx1kZ7ygrhbLR1X-1).

the display logic:
if `property.access_process = "Private Land Use Agreement"` then set it as the blue `Best Option` card,
otherwise, set it as `unavailable`

if `property.access_process = "Land Bank"` then set it as the blue `Best Option` card,
otherwise, set it as `unavailable`

if `property.access_process = "Buy Property"` then set it as the blue `Best Option` card,
otherwise, check to see if its cheaper than $1000, if so, set it as `available`
otherwise, set it as `unavailable`

if `property.side_yard_eligible = "Yes"` then set it as the yellow `neighbors` card,
otherwise, set it as `unavailable`

if `property.tactical_urbanism = "Yes"` then set it as `available`,
otherwise, set it as `unavailable`

if `property.conservatorship = "Yes"` then set it as `available`,
otherwise, set it as `unavailable`

## Test

You can test this by selecting filters of the properties, and seeing that the properties returned have matching information

## Demo

https://github.com/CodeForPhilly/vacant-lots-proj/assets/8061917/330cf879-ac33-4b11-a784-ba969f89eb2a

### CODE REVIEW

**Comment by paulhchoi** [comment]
@thansidwell what should the "Quick Cleaning" link to on the `/get-access` page? seemed like everything had a logical match except for that

**Comment by thansidwell** [comment]
@paulhchoi This looks amazing! 

We haven't written the panel for "Quick Cleaning" yet. So we probably shouldn't link anywhere. Taking them to the Get Access page would confuse them. I'll work with Nissim to get it written and then we can make it a link. 

- Remove the link on "Quick Cleaning" 
- Add a link "Get Access" on the sentance "Learn more on Get Access."

**Comment by paulhchoi** [comment]
> @paulhchoi This looks amazing!
> 
> We haven't written the panel for "Quick Cleaning" yet. So we probably shouldn't link anywhere. Taking them to the Get Access page would confuse them. I'll work with Nissim to get it written and then we can make it a link.
> 
> * Remove the link on "Quick Cleaning"
> * Add a link "Get Access" on the sentance "Learn more on Get Access."

@thansidwell good call, both fixes made. I also removed the right caret ">" on the Quick Cleaning card given it doesn't link anywhere

**Comment by paulhchoi** [comment]
@thansidwell oh sorry I forgot to mention, I added in a change for the "Best/Available" Chip component when viewing on tablet viewports to tuck under the copy, as it squeezed out the copy too much. this wasn't something you drew up tho so open to changes:


https://github.com/CodeForPhilly/vacant-lots-proj/assets/8061917/76b0fb62-0171-433b-9207-e6b0d67e6a00

**Comment by thansidwell** [comment]
@paulhchoi Beautiful! That's perfect. Thanks for thinking of that. 

Also are the 'chips' or what I've been calling 'badges' the same as the one's used in for the priority? Ideally they would be. Just some have icons and some don't. 

CleanShot 2024-04-18 at 21 05 20@2x

**Comment by paulhchoi** [comment]
> @paulhchoi Beautiful! That's perfect. Thanks for thinking of that.
> 
> Also are the 'chips' or what I've been calling 'badges' the same as the one's used in for the priority? Ideally they would be. Just some have icons and some don't.

yep they are, Next-ui just happens to call them Chips, eg:

component for the priority:
```
  <Chip
    classNames={{
      base: `${priorityClass} border-small border-white/50`,
      content: "body-sm",
    }}
  >
    {priority_level + " Priority"}
  </Chip>
```

component for the options:
```
<Chip
  startContent={<PiStar size={18} />}
  classNames={{
    base: `bg-[#BAE4F5] text-[#003144] flex flex-row space-x-1 py-[3px] px-[6px]`,
    content: "body-sm",
  }}
>
  Best Option
</Chip>
```

**Comment by thansidwell** [comment]
@paulhchoi Nice! Thanks.

**Comment by paulhchoi** [comment]
> if a property is `access_process == 'Private Land Use Agreement'`, then the land use agreement chip should be "best option" and the "buy property" should be "available".

@nlebovits Just double checking here, isn't the "Buy Affordably from Owner" only for properties that are less than $1000? So you're saying if the access_process is "Private Land Use Agreement", then buy property should be available, regardless of its market price?

**Comment by Moylena** [comment]
@paulhchoi  flagging a conflict!

**Review by thansidwell — CHANGES_REQUESTED** [review]
@paulhchoi  
Right now properties are showing up with two "Buy Affordably from Owner" options one marked available and one unavailable. On properties both above and below $1,000. 

CleanShot 2024-04-19 at 16 53 52@2x

CleanShot 2024-04-19 at 16 45 58@2x

CleanShot 2024-04-19 at 16 46 44@2x

I would assume if the property is over $1,000 it should be disqualified from "Buy Affordably from Owner."

**Review by brandonfcohen1 — APPROVED** [review]

**Pull request merged**
