### PR TITLE
Fix #477: Updated navbar for breakpoints between 640px and 850px

### LINKED ISSUE #477: Usability: Logo shrinks on small screens
When the user's browser width is between 850px and 640px, looking at the Nav header, 

- the logo becomes smaller 
- the top and bottom padding becomes smaller as well.  

Image

Here's a video illustrating the issue. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/2fc36510-c4f4-4e70-add8-bd06cb0dd09f

On Safari in addition

- the whole website scales down on a smaller screen. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/524b8d7e-b9be-4101-90df-864aef458073

Make these fixes

- Adjust the navigation breakpoint so it breaks to the mobile view of the navigation eariler. Perhaps around 850px. 
- Stop the logo or top and right padding from becoming smaller. 
- Stop the website from scaling down on small screens. Appears to only sometimes be an issue on Safari. [Something like this](https://stackoverflow.com/questions/7078663/how-do-make-a-mobile-web-page-not-shrink) might be the fix.

### PR DESCRIPTION
**Pull request by amyyeung17**
## Description
This PR addresses issue #477. I fixed few small inconsistencies including the dropdown position.

### Chrome

https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/2fc1a552-1b0b-43be-9200-3703a7e6800f

### Safari

https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/34f4d7a3-a16d-4eb4-b930-2ab3990a13ad

### CODE REVIEW

**Comment by amyyeung17** [comment]
@thansidwell The navbar's background was blurred when scrolling on larger screens but only partially on smaller screens. I ended up removing the blur for the latter to maintain consistency. Is there a preference?

**Comment by thansidwell** [comment]
@amyyeung17 Could we have the blur appear on both desktop and mobile?

**Comment by amyyeung17** [comment]
@thansidwell Done!

**Review by thansidwell — APPROVED** [review]
Looks great!

**Pull request merged**
