### PR TITLE
#288 and #449 Fix Button Inconsistency and Update Some Buttons to Primary

### PR DESCRIPTION
**Pull request by BayLadyCoder**
#288 
- Created new `ThemeButton` and `ThemeButtonLink` to be used across the app for button consistency.
- Replaced all buttons (exclude nav buttons) with the new `ThemeButton` for regular buttons or `ThemeButtonLink` for links
- `ThemeButton` shows as `<button>` with `type="button"`
- `ThemeButtonLink` shows as `<a>` with `role="link"`

#449 
- Updated some buttons to be primary buttons (`Learn How` and `Get Started` buttons on the landing page and `Done` button in the map filter)

All Button States

https://github.com/CodeForPhilly/vacant-lots-proj/assets/33296817/93cc6247-b745-44a7-8443-d240c078ef09

Button vs ButtonLink in DOM

https://github.com/CodeForPhilly/vacant-lots-proj/assets/33296817/985944ab-97c3-45a4-b7de-e8cb05b96e91

# Landing Page
LearnHow
LandingPageButtons
GetStarted

# Map Filter
SidePanelControlBar
FilterDone

# Single Property Detail Page
SinglePropertyDetails
StreetViewCloseButton

# Example Code for Developers
Screen Shot 2024-03-29 at 5 46 11 PM

```
    <div className="flex justify-center items-center gap-2 my-2">
          <ThemeButton label="Primary" startContent={<PiPlus />} />
          <ThemeButton label="Primary" endContent={<PiPlus />} />
          <ThemeButton startContent={<PiPlus />} aria-label="Add new item" />
          <ThemeButton
            label="Primary Disabled"
            disabled={true}
            startContent={<PiPlus />}
          />
     </div>
     <div className="flex justify-center items-center gap-2 my-2">
          <ThemeButton
            color="secondary"
            label="Secondary"
            startContent={<PiPlus />}
          />
          <ThemeButton
            color="secondary"
            isDisabled={true}
            label="Secondary Disabled"
            startContent={<PiPlus />}
          />
          <ThemeButton
            color="secondary"
            isSelected={true}
            label="Secondary Selected"
            startContent={<PiPlus />}
          />
          <ThemeButton
            color="secondary"
            isSelected={true}
            isDisabled={true}
            label="Secondary Selected Disabled"
            startContent={<PiPlus />}
          />
    </div>
    <div className="flex justify-center items-center gap-2 my-2">
          <ThemeButton
            color="tertiary"
            label="Tertiary"
            startContent={<PiPlus />}
          />
          <ThemeButton
            color="tertiary"
            disabled={true}
            label="Tertiary Disabled"
            startContent={<PiPlus />}
          />
          <ThemeButton
            color="tertiary"
            isSelected={true}
            label="Tertiary Selected"
            startContent={<PiPlus />}
          />
          <ThemeButton
            color="tertiary"
            isSelected={true}
            isDisabled={true}
            label="Tertiary Selected Disabled"
            startContent={<PiPlus />}
          />
    </div>
    <div className="flex justify-center items-center gap-2 my-5">
          <h3 className="text-lg mr-3">Link Buttons ---></h3>
          <ThemeButtonLink
            href="#"
            label="Find Properties"
            startContent={<PiBinoculars />}
          />
          <ThemeButtonLink
            href="#"
            label="Get Access"
            color="tertiary"
            startContent={<PiKey />}
          />
          <ThemeButtonLink
            href="#"
            isSelected={true}
            label="Find Properties"
            color="tertiary"
            startContent={<PiBinoculars />}
          />
    </div>
```

### CODE REVIEW

**Comment by BayLadyCoder** [comment]
Hi, @thansidwell and @paulhchoi! This PR is ready to be reviewed. Thank you!

**Comment by BayLadyCoder** [comment]
Converted this to draft for now. Working on reducing CSS classes on the `ThemeButton` according to @thansidwell feedback.

**Comment by thansidwell** [comment]
@paulhchoi or @brandonfcohen1, could you authorize @BayLadyCoder to depoy this commit? https://github.com/CodeForPhilly/vacant-lots-proj/pull/479#issuecomment-2026325404

**Comment by brandonfcohen1** [comment]
> @paulhchoi or @brandonfcohen1, could you authorize @BayLadyCoder to depoy this commit? [#479 (comment)](https://github.com/CodeForPhilly/vacant-lots-proj/pull/479#issuecomment-2026325404)

deployed, sorry for the delay!

**Review by brandonfcohen1 — CHANGES_REQUESTED** [review]
@BayLadyCoder can you fix merge conflicts?

**Review by thansidwell — APPROVED** [review]
From a visual standpoint, all the buttons look great!

**Comment by BayLadyCoder** [comment]
I messed up git, so I'm gonna create a new branch and a new PR for this.

**Pull request closed without merging**
