### PR TITLE
287 accessible color palette

### PR DESCRIPTION
**Pull request by Amberroseweeks**
Adding in colors from the figma mockup to update UI so that contrast levels meet 4.5:1 ratio. I edited the tailwind config to match hex values documented in the Figma components. The main change you will see will be on the property card chips on the map page.

The color palette is pretty simple so I don't think we need to do much mapping here, we've been using tailwind classes pretty consistently so I couldn't find instances of hard coded colors to convert. 

I ran the pages through WAVE and have not found any color contrast errors. 

Screen Shot 2024-03-20 at 5 22 54 AM

This closes issue https://github.com/CodeForPhilly/vacant-lots-proj/issues/287

### CODE REVIEW

**Comment by Amberroseweeks** [comment]
Converting to a draft because i'd like to add more colors for link styles as well

**Comment by brandonfcohen1** [comment]
@Amberroseweeks is this ready for review again?

**Comment by Amberroseweeks** [comment]
> @Amberroseweeks is this ready for review again?

Yes, this is ready for review

**Comment by brandonfcohen1** [comment]
@bacitracin will let you review this one

**Review by marvieqa — APPROVED** [review]
Looks good! Ready to ship!

**Pull request merged**
