### PR TITLE
Styling: Adjust table column width

### LINKED ISSUE #305: Styling: Adjust table column width
The first table column is so narrow it's causing a lot of text wrapping to the next line. 

Widen that column so it doesn't wrap. 

Image

### PR DESCRIPTION
**Pull request by ajtw7**
This behavior is due to the class that is currently being used for the <th> tag (table header).

- [x] changed the table header class from w3/12 to w4/12.

Closes #305

### CODE REVIEW

**Comment by ajtw7** [comment]
FYI: the majority of the changes are auto-formatting, swapping single quotes for double.

**Comment by nlebovits** [comment]
@bacitracin @marvieqa y'all can merge once @thansidwell has ok'd it

**Comment by bacitracin** [comment]
Hey @ajtw7! I took a peek and it looks good, but do you mind updating the base branch to `staging`?

**Comment by nlebovits** [comment]
@bacitracin @ajtw7 I corrected the base branch but it looks like there are conflicts w `staging`. I'll let you resolve + merge.

**Comment by ajtw7** [comment]
@nlebovits & @bacitracin, should I submit another commit w/  the changes to correct the merge conflicts (single quotes vs double quotes), 
or is this something I shouldn't worry about?

**Comment by bacitracin** [comment]
@ajtw7 @thansidwell still needs to have a look, so just add another commit fixing the conflict. I think the other conflict is that the className on the a tag should be link instead of text-primary.

**Comment by brandonfcohen1** [comment]
For the formatting, refer to oru formatting guide here: https://github.com/CodeForPhilly/vacant-lots-proj/blob/main/docs/SETUP/FRONT_END.md#formatting

**Comment by paulhchoi** [comment]
hey @ajtw7 , have you considered the use of `whitespace-nowrap` to go along with your static width class? As your PR stands, if the viewport width gets under about 1170px, some of the longer headers will still wrap — see examples attached

without `whitespace-nowrap` at ~1170px veiwport:
Screenshot 2024-03-05 at 2 01 47 AM

with `whitespace-nowrap` at ~760px viewport:
image

**Review by brandonfcohen1 — CHANGES_REQUESTED** [review]
Please address merge commits and use updated linting that we've just introduced into `staging`, thank you!

**Comment by thansidwell** [comment]
Looking at this preview it all looks great too me!
(https://vercel.live/open-feedback/vacant-lots-proj-git-fork-ajtw7-a-87f418-clean-and-green-philly.vercel.app?via=pr-comment-visit-preview-link&passThrough=1) 

CleanShot 2024-03-08 at 15 04 10@2x

**Comment by ajtw7** [comment]
@brandonfcohen1 can this PR be closed since the work has already been done in https://github.com/CodeForPhilly/vacant-lots-proj/pull/367 ?

**Comment by paulhchoi** [comment]
closing as addressed in https://github.com/CodeForPhilly/vacant-lots-proj/pull/367

**Pull request closed without merging**
