### PR TITLE
#475 Shifted map search down and to left, shifted legend to right 

### PR DESCRIPTION
**Pull request by AZBL**
This update added styles to global.css to shift the map search bar down 20px and to the left 20px and shift the map legend right 20x. 

1. **Shifted the Map Search Bar Down and to the Left:** Targeted #main .maplibregl-ctrl-top-right to move the search down and to the left 20px. While the issue description did not specify moving it to the left this was reflected in the prototype design.

2. **Shifted the Map Legend to the Right:**  Targeted #main .maplibregl-ctrl-bottom-left to move the legend right 20px. Of note, on smaller screens the attribution does cover the legend some so perhaps this can be looked into.

### CODE REVIEW

**Comment by AZBL** [comment]
@Moylena @thansidwell

**Comment by brandonfcohen1** [comment]
@thansidwell can you review?

**Comment by AZBL** [comment]
Hi I removed the following from global css: 

/* Space between search bar and sidepanel, especially for small screens */
.mapboxgl-ctrl-geocoder {
  @apply mt-2;
}

@paulhchoi

**Review by paulhchoi — APPROVED** [review]
lgtm, thanks for the update! 👍

**Review by thansidwell — CHANGES_REQUESTED** [review]
For some reason, there's an extra gap on Safari. It looks correct on Chrome. 

CleanShot 2024-04-10 at 16 00 47@2x

**Comment by thansidwell** [comment]
Hey @AZBL! Just checking on the status of this. It looks like you have some conflicts. I noticed the properties and search don't load in the preview.

**Comment by AZBL** [comment]
Hey @thansidwell I just addressed the conflicts so now the properties and search load again. 
As far as the chrome vs. safari issue I think I might need some assistance from @paulhchoi or someone else on that, as I'm not sure the best way to go about fixing it.

**Comment by thansidwell** [comment]
@AZBL I'm fine with you merging these changes. The issue is still on Safari, but I don't think that should hold it up.

**Review by brandonfcohen1 — APPROVED** [review]

**Pull request merged**
