### PR TITLE
Fix #526, #534: Content pages resize consistently 

### LINKED ISSUE #526: Styling: Smooth out content container resizing
As you adjust the content container width snaps to certain breakpoints. 

- The margins can be very wide at certain breakponts and very narrow at others, appearing awkward.
- The content container is sometimes smaller than it needs to be, not filling the space optimally. 
- Resizing appears very jumping and rigid. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/4c76ed1c-4f7c-45aa-b038-c43f9a3a77a3

Change the experience so that...

- The left/right margin stays consistent. 
- The content fills the avaliable space well.  
- When resizing it's much more fluid.

I messed with the CSS, taking out some classes and was able to achieve close to what I believe we need. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/c564baf7-848b-45b5-a486-aa25aa4b230e

### PR DESCRIPTION
**Pull request by amyyeung17**
## Description
This PR addresses issue #526 & #534. 

## Testing/Proof

https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/4bedf2ab-2a65-44f7-96b2-0e7c82ca7d61

### CODE REVIEW

**Comment by amyyeung17** [comment]
@thansidwell Some content in the access page overflow due to the urls in the text. Should they be replaced with links? The only problem is they'll be on a blue background.

**Comment by thansidwell** [comment]
@amyyeung17 

There's just one issue I see. One the home page the top padding is 100px, not 60px like the others. 

CleanShot 2024-04-18 at 12 54 45@2x

Yes, the long URL should be replaced with anchor links. I'll write I ticket to do that. I'll check if the blue text on light blue background will pass.

**Comment by amyyeung17** [comment]
@thansidwell Whoops, fixed that.

**Comment by Moylena** [comment]
@amyyeung17  I believe this one needs an update?

**Comment by amyyeung17** [comment]
@Moylena As in the task? Also do we want to make the padding on the bottom consistent with the top (60px)?


https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/55f66513-634a-4124-a792-e6e41a3e6cc5

**Comment by thansidwell** [comment]
@amyyeung17 @Moylena  

- No, let's no change the padding on the bottom of the page. That's the footer and it works fine. 
- The padding in your video looks correct, but when I look at the preview it's still not correct. 

CleanShot 2024-04-19 at 12 51 47@2x

**Comment by amyyeung17** [comment]
@thansidwell Oh, are you perhaps looking at yesterday's deploy? The most recent commit "Fixed landing page" hasn't been authorized yet.

**Review by thansidwell — APPROVED** [review]
I'll approve this since the video looks perfect.

**Pull request merged**
