### PR TITLE
443 About content and styling

### PR DESCRIPTION
**Pull request by cozyfestiv**
This PR is for #443 Content + Styling the About Page

Updated the copy and formatting to match the Figma prototype. I'm not quite sure about the gap at the bottom, I couldn't seem to get it to shrink so it's a little bloated. 

I added the photos and graphics to the public folder. I also included code to link to the gentrification page at the end of concerns but as far as I understand, it doesn't currently exist so I commented it out so there's no dead link there. 

Let me know if there's anything to tweak or that I missed. This is my first PR and from what I got from the meeting that means I'm supposed to tag Arielle and the contributor bot, but I don't see either of them when I do a mention. 

Thanks, everyone!

Screen Shot 2024-03-21 at 12 09 34

### CODE REVIEW

**Comment by thansidwell** [comment]
@cozyfestiv Great work! Here are some corrections. 

- You can take out the "Concerns" section. Talking with Nissim a better location is on the Transform page. 
- The images for "Our Vision" and "Our Methodology" are stretched. I assume it's because you weren't able to export the images from Figma. Can you swap in all the images with the images in the ZIP file attached? 
[Archive.zip](https://github.com/CodeForPhilly/vacant-lots-proj/files/14705545/Archive.zip)

**Review by thansidwell — CHANGES_REQUESTED** [review]
@cozyfestiv Great work! Here are some corrections.

You can take out the "Concerns" section. Talking with Nissim, we shifted it to the Transform page. I updated the [prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592%3A31549&mode=design&t=rwvoZG2F2y3A2hfM-1).
The images for "Our Vision" and "Our Methodology" are stretched. I assume it's because you weren't able to export the images from Figma. Can you swap in all the images with the images in the ZIP file attached?
[Archive.zip](https://github.com/CodeForPhilly/vacant-lots-proj/files/14705545/Archive.zip)
Some of the images have borders that don't look right. https://share.cleanshot.com/lgglVsbF I think it might be best to do the images the way the home page did them, which I think is using divs with background image and adding the border-radius to that.

**Comment by cozyfestiv** [comment]
Ok, I re-inserted the "Our Vision" and "Our Methodology" photos, so they are at their original ratios.
Removed Concerns section 
Removed borders from all photos except the research one, since that is actually how the prototype was originally.

Let me know if there's anything else!

**Review by thansidwell — APPROVED** [review]

**Comment by thansidwell** [comment]
@cozyfestiv Looks great!

**Pull request merged**
