### PR TITLE
415: Feature: Save properties

### LINKED ISSUE #415: Feature: Save properties
Currently there is no way to save a property in the property detail page

Please add the icon in the top right hand of the property detail card, on the same line as the "back" link. Include the default and active state as a part of this ticket 

Image

Image

When user clicks this new icon, all properties with this "save" flag will appear. It's another filtering mechanism. 

--- 

See Figma file for details: 
https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-30687&t=sdhkPVHItWMM3Xnn-0&scaling=min-zoom&page-id=187%3A12602&starting-point-node-id=2592%3A30019

### PR DESCRIPTION
**Pull request by CodeWritingCow**
## Description
This PR adds a "Save" button to the property details UI. When users click the button, it saves the property to their Web browser's local storage. They can "unsave" the property by clicking the button again.

This PR also adds a "Saved" button to the property list UI. When users click the button, it filters the list of properties to those saved in local storage.

## Screenshots

Screenshots coming soon.

Closes #415

### CODE REVIEW

**Comment by nlebovits** [comment]
Thanks, @CodeWritingCow! Now that we have this, @thansidwell can you come up with a banner component to show a data storage notice for users? 

Also, @all-contributors, please add @CodeWritingCow for code :)

**Review by paulhchoi — APPROVED** [review]
Working well for me on local, great job @CodeWritingCow! There are a few nits in terms of abstracting some of the localStorage access functions into a separate file to make transitioning away to something like db's easier in the future, as well as using an enum for the localStorage key instead of hardcoding the string, but in terms of working code that would be ready for the competition this friday, I'm ok with this PR 👍

**Comment by thansidwell** [comment]
Hey @CodeWritingCow! @nlebovits merged your work into Staging and Production/Live before I had a chance to look at it. I assume he just wanted to rush whatever work you did for the competition even if it has issues. 

Here's the issues I found. 

- When you save properties and then view the list of properties the "# Properties in View" count is widely inaccurate. Sometimes properties seem to count for 1 to 3 properties. 
- When you filter by "Saved" properties the fitler button changes to a selected state and adds "(1)." Viewing the Saved properties should not change the filter button at all. They should be indepedant. 
- The height of properties fills the space in an odd way. The cards should shrink to fit the content. 

https://github.com/CodeForPhilly/clean-and-green-philly/assets/1965986/26f28aae-0796-40f7-97e6-02b3e0b11d46

**Comment by CodeWritingCow** [comment]
@nlebovits and @paulhchoi thanks for the feedback! After the competition, I can improve this feature as you recommend (ex. using enum for localStorage key, and refactoring localStorage access functions into a separate file). I can create a GitHub issue for this if it doesn't exist yet.

**Comment by CodeWritingCow** [comment]
@thansidwell thanks for catching the issues! I was able to replicate them. I am looking into their cause and will submit a PR to fix them as soon as I can.

**Comment by CodeWritingCow** [comment]
@thansidwell Another update: I also debugged the issue with the Filter button. The UI was including `OPA_ID` in filterCount, the tally of filters. This is default behavior, since OPA_ID is technically being used as a filter). To fix this, I am excluding OPA_ID from the count if a user is viewing a list of saved properties.

I also looked into the issue with extra space in the property card UI. I believe this issue is pre-existing and separate from the Save button feature. To confirm this, I filtered the list of results down to one property (without saving any property to localStorage). The card UI still has extra space. See screen recording: https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/817e410f-2a68-4722-b791-4e2f473dcc78 ... Can we create a separate bug or improvement ticket for removing the extra space?

**Comment by thansidwell** [comment]
@CodeWritingCow Yeah, I'll write a ticket to fix the extra space issue. 

Just publish a Vercel preview and ask for approval! 

Thanks!

**Comment by CodeWritingCow** [comment]
@thansidwell I don't have authorization to publish a Vercel preview in this repo. Can an admin do it for my PR?

**Pull request merged**
