### PR TITLE
feat(279): refactor text styles and add enforcement via eslint

### LINKED ISSUE #279: Styling: Fix text styles
Right now the text appears in all different sizes which gives an uneven, haphazard feeling. https://share.cleanshot.com/wSCPdJbF

We need to add a type scale system and text styles. 

- Here's the type scale we can use. I built it with an online tool.  [Open link](https://www.fluid-type-scale.com/calculate?minFontSize=16&minWidth=400&minRatio=1.125&maxFontSize=16&maxWidth=1280&maxRatio=1.3&steps=sm%2Cmd%2Clg%2Cxl%2C2xl%2C3xl&baseStep=md&prefix=font-size&decimals=2&includeFallbacks=on&useRems=on&remValue=16&previewFont=Inter&previewText=Almost+before+we+knew+it%2C+we+had+left+the+ground&previewWidth=1920). 
- This type scale dynmatically changes size depending on the size of the device that's using it. It's a more elegant alternative to breadpoint changes. https://share.cleanshot.com/mMV25cpW
- It used CSS clamp which seems to have sufficent support. https://share.cleanshot.com/wXK6sJP0  
- Here's the text styles I'd like to use, built on that type scale. https://share.cleanshot.com/qNjSzRNf
- I roughed out what the CSS might be. [text-styles.css.zip](https://github.com/CodeForPhilly/vacant-lots-proj/files/14040245/text-styles.css.zip)

Next, apply these classes all throughout the site. 

- Landing page https://share.cleanshot.com/7zJhPJnB
- Find Properties https://share.cleanshot.com/dpV4xQWH
- Filter https://share.cleanshot.com/fFfg0gPR
- Property https://share.cleanshot.com/s1dbbFDX
- Content pages (Get Access, Transform a Property, Summary, Methodology) https://share.cleanshot.com/1X6mPr80

Here's the CSS to support this. 
```
/* Fluid font size variables, for browsers that support clamp */

@supports (font-size: clamp(1rem, 1vw, 1rem)) {
  :root {
    --font-size-sm: clamp(0.89rem, -0.22vw + 0.94rem, 0.77rem);
		--font-size-md: clamp(1rem, 0vw + 1rem, 1rem);
		--font-size-lg: clamp(1.13rem, 0.32vw + 1.05rem, 1.3rem);
		--font-size-xl: clamp(1.27rem, 0.77vw + 1.07rem, 1.69rem);
		--font-size-2xl: clamp(1.42rem, 1.41vw + 1.07rem, 2.2rem);
		--font-size-3xl: clamp(1.6rem, 2.28vw + 1.03rem, 2.86rem);
  }
}
/* Fallback variables for browsers that don't support clamp */
@supports not (font-size: clamp(1rem, 1vw, 1rem)) {
  :root {
    --font-size-sm: 0.89rem;
		--font-size-md: 1rem;
		--font-size-lg: 1.13rem;
		--font-size-xl: 1.27rem;
		--font-size-2xl: 1.42rem;
		--font-size-3xl: 1.6rem;
  }
  @media screen and (min-width: 1280px) {
    :root {
      --font-size-sm: 0.77rem;
			--font-size-md: 1rem;
			--font-size-lg: 1.3rem;
			--font-size-xl: 1.69rem;
			--font-size-2xl: 2.2rem;
			--font-size-3xl: 2.86rem;
    }
  }
}
.heading-3xl {
	font-size: var(--font-size-3xl);
	font-family: var(--font-family);
	font-weight: 800;
}
.heading-2xl {
	font-size: var(--font-size-2xl);
	font-family: var(--font-family);
	font-weight: 800;
}
.heading-xl {
	font-size: var(--font-size-xl);
	font-family: var(--font-family);
	font-weight: bold;
}
.heading-lg {
	font-size: var(--font-size-lg);
	font-family: var(--font-family);
	font-weight: bold;
}
.heading-md {
	font-size: var(--font-size-md);
	font-family: var(--font-family);
	font-weight: bold;
}
.body-lg {
	font-size: var(--font-size-lg);
	font-family: var(--font-family);
	font-weight: regular;
}
.body-md {
	font-size: var(--font-size-md);
	font-family: var(--font-family);
	font-weight: regular;
}
.body-sm {
	font-size: var(--font-size-sm);
	font-family: var(--font-family);
	font-weight: regular;
}
```

### PR DESCRIPTION
**Pull request by paulhchoi**
## Description
This PR adds an eslint rule to enforce classname usages of `heading-*` and `body-*` classes over `text-*` size classes, and updates the font sizes across the app to conform to this style guide. 

## Testing eslint rule updates
If a user adds tailwind font size classes of `text-sm` to `text-9xl` to any element, they should receive an eslint warning of: ```Use `heading-*` or `body-*` classes instead of specific `text-` size classes.eslint(custom-rules/no-text-size-class)```

image

## Testing UI changes
Due to the reach of these changes, screenshots won't be explicitly included, but the reviewer should test by opening these files as provided in the acceptance criteria, and seeing that the styles and sizings match (as described in https://github.com/CodeForPhilly/vacant-lots-proj/issues/279):
> - Landing page https://share.cleanshot.com/7zJhPJnB
> - Find Properties https://share.cleanshot.com/dpV4xQWH
> - Filter https://share.cleanshot.com/fFfg0gPR
> - Property https://share.cleanshot.com/s1dbbFDX
> - Content pages (Get Access, Transform a Property, Summary, Methodology) https://share.cleanshot.com/1X6mPr80

Closes #279

### CODE REVIEW

**Comment by brandonfcohen1** [comment]
Thanks @paulhchoi! This has long been needed. Can you fix the merge conflict then I'll review?

**Comment by paulhchoi** [comment]
> Thanks @paulhchoi! This has long been needed. Can you fix the merge conflict then I'll review?

Just fixed 👍

**Review by brandonfcohen1 — APPROVED** [review]
This is really great, thanks @paulhchoi!

@thansidwell and @nlebovits are going to reach out to see if you want to get more involved.

**Comment by nlebovits** [comment]
@all-contributors please add @paulhchoi for code

**Comment by thansidwell** [comment]
Hey @paulhchoi and @brandonfcohen1! I just found time to look at the [preview](https://vercel.live/open-feedback/vacant-lots-proj-git-fork-paulhch-da4af4-clean-and-green-philly.vercel.app?via=pr-comment-visit-preview-link&passThrough=1). It looks great! I don't see any issues.

**Pull request merged**
