### PR TITLE
486: Map behavior after property search

### PR DESCRIPTION
**Pull request by jgrimes86**
This addresses issue #486 

When a user searches for a property in the map's search bar, the map shifts to the property and a tooltip appears marking the property.

If the searched-for property is vacant, the side panel changes to the property details.  If the property is not vacant, the side panel remains in the list view or (if it was previously showing another property's details) returns to the list view.

@thansidwell - I don't see any details about whether a zoom level should be set for the search result, so as of now the zoom level does not change when a property is searched.

Also, I thought I saw an assigned ticket that was handling the styling of the map tooltip.  I can't find it now and don't see changes on staging site, so if I was imagining that please let me know and I'll work on the tooltip styling.

@paulhchoi and @brandonfcohen1 - For properties that are out of view when they are searched, I had some trouble checking whether they are in the dataset of vacant properties .  My solution was to delay calling the 'handleMapClick' function (which I'm re-purposing for the search) with a setTimeout() with a 0.5 second delay.  I don't know if that's best practice, or enough time/too little time, but I couldn't get it to work otherwise.

### CODE REVIEW

**Review by brandonfcohen1 — CHANGES_REQUESTED** [review]
hey @jgrimes86 - check out how I do it with the routing here: https://github.com/CodeForPhilly/vacant-lots-proj/blob/129446d8660c0a149b0ab244561ce4054aa9942b/src/app/find-properties/%5B%5B...opa_id%5D%5D/page.tsx#L58-L117

**Comment by jgrimes86** [comment]
Thank you for the pointer @brandonfcohen1.  I think I have it working with now with a useEffect.  I'm going to test it out a little more tomorrow morning when I'm fresh, then I should have an improved version for you to review.

**Comment by thansidwell** [comment]
@jgrimes86 This works great!

And yes, the zoom should just stay as it is. That's the same behavior we use as someone clicks on properties on the map or the list. We might consider it after testing it out a lot, but this seems best for now.

**Comment by jgrimes86** [comment]
@brandonfcohen1 - I've changed the function for handling map searches to a useEffect and added state for `searchedProperty` to store the searched property info.  The useEffect runs after updates to featuresInView and selectedProperty, and it returns nothing if featuresInView doesn't exist, there is already a selectedProperty, or searchedProperty's address is '' (which I'm using as the default/non-searched property value).

Since a search's selectedProperty is being set by the new useEffect, I've changed `handleMapClick` back to its previous form.

**Review by brandonfcohen1 — APPROVED** [review]
looks great- will let @thansidwell make a new ticket if he thinks the zoom level should be changed

**Pull request merged**
