### PR TITLE
Landing page and filter view

### PR DESCRIPTION
**Pull request by JosephAni**
Modified styling of landing and filter view page content and buttons.
filter
landing

### CODE REVIEW

**Comment by nlebovits** [comment]
@brandonfcohen1 can we get a review on this PR? sorry @JosephAni for letting it take so long--might be out of date by now

**Review by brandonfcohen1 — CHANGES_REQUESTED** [review]
@JosephAni can you fix merge commits and merge in the latest `staging` so you get the proper linting that we have set up?

**Comment by nlebovits** [comment]
@JosephAni I just changed the merge to `staging` for you. if you can get the conflicts resolved, we can go ahead and merge it :)

**Comment by brandonfcohen1** [comment]
@JosephAni do you have an update here? otherwise I will close

**Comment by JosephAni** [comment]
Pls close.

**Pull request closed without merging**
