### PR TITLE
Fix #458: change filter toggle experience and buttons 

### LINKED ISSUE #458: Usability: Change filter to a toggle/disclusure experience
Current when a user clicks "Filter" the whole right panel is swaped for the filter controls. They have to click Done to go back. This takes the user out of the context they were just in and could likely be disorienting. Make these changes to avoid that. 

- When a user clicks filter, keep the map list controls visible above so the user doesn't lose context of where they are and what they are doing. 
- When a user clicks the "Filter" button and the filter opens, change it to the selected state. When they click the Filter button again the filter should close and the button should back to its default state. 
- Change the "Done" button to a X icon without text. Clicking this will also close the filter. It's a more common way to get out of a view. 

Image

### PR DESCRIPTION
**Pull request by amyyeung17**
## Description
This PR addresses #458. 

Filter tab changes:
- Sticky nav bar persists when on tab
- Respective nav button now has an active state and be clicked to exit 
- Done is replaced with X icon for exit button

### Desktop to mobile

https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/74c4eb2a-865b-4b71-b6e1-56f6b5cdc93f

### CODE REVIEW

**Comment by bacitracin** [comment]
The sidebar is looking good, just a couple notes.
- Can you add an `aria-label="Close filter panel` to the X button please?
- Looks like there's a bottom border for the sticky header in the design that's missing

**Comment by amyyeung17** [comment]
@bacitracin Addressed your comments and also fixed the double scroll problem with the property detail sections. The parent div in PropertyCard.tsx (className="sm:max-w-sm w-full lg:w-1/2...") is just for aligning the actual card, so I relocated its handleClick to its child div (the card itself). 




https://github.com/CodeForPhilly/vacant-lots-proj/assets/28910543/4eeb2ceb-7d6c-4e1c-b1da-e4d2c2a213ae

**Review by brandonfcohen1 — CHANGES_REQUESTED** [review]
@amyyeung17 can you resolve merge conflicts?

**Comment by brandonfcohen1** [comment]
deployment failed

```
Type error: Cannot find module '@/app/map/page' or its corresponding type declarations.
  3 | import { Button } from "@nextui-org/react";
  4 | import { PiX } from "react-icons/pi";
> 5 | import { BarClickOptions } from "@/app/map/page";
    |                                 ^
  6 |
  7 | const filters = [
  8 |   {
Error: Command "npm run build" exited with 1
```

**Comment by amyyeung17** [comment]
@brandonfcohen1 My bad, it should be good now.

**Comment by brandonfcohen1** [comment]
@bacitracin can you approve?

**Comment by bacitracin** [comment]
@amyyeung17 I might have missed this on the first iteration, but it looks like the Filter screen is no longer scrollable. On short screens or mobile users won't be able to reach the bottom filter options.

**Comment by amyyeung17** [comment]
@bacitracin Whoops, fixed.

**Review by bacitracin — APPROVED** [review]
Thank you for the updates

**Review by brandonfcohen1 — APPROVED** [review]

**Pull request merged**
